steps:
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: bash
  args:
  - '-eEuo'
  - 'pipefail'
  - '-c'
  - |-
    curl -L "https://github.com/docker/compose/releases/download/1.28.5/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
    curl https://raw.githubusercontent.com/canha/golang-tools-install-script/master/goinstall.sh | bash
    source /builder/home/.bashrc
    apt-get update && apt-get install gcc -y
    ./run-tests.sh unit
    ./run-tests.sh integration
