version: '3.0'
services:
  websu-api:
    image: samos123/websu-api:latest
    ports:
    - "8000:8000"
    environment:
    - "LIGHTHOUSE_SERVER=lighthouse-server:50051"
    - "MONGO_URI=mongodb://mongo:27017"
    - "SERVE_FRONTEND=false"
    - "AUTH=firebase"
    - "GOOGLE_APPLICATION_CREDENTIALS=/firebase-sa.json"
    volumes:
      - ./firebase-sa.json:/firebase-sa.json
    links:
    - mongo
    - lighthouse-server
  lighthouse-server:
    image: samos123/lighthouse-server-docker:latest
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    ports: 
    - "127.0.0.1:50051:50051"
  mongo:
    image: mongo:4
    ports: 
    - "127.0.0.1:27017:27017"
