name: Build and deploy to production

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
    - name: go test ./...
      run: |
          sudo npm install -g lighthouse@9.4.0
          ./run-tests.sh unit
    - name: integration tests
      run: |
          ./run-tests.sh integration
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      with:
        buildkitd-flags: --debug
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Login to GAR
      uses: docker/login-action@v1
      with:
        registry: us-central1-docker.pkg.dev
        username: _json_key
        password: ${{ secrets.GAR_SA }}
    - name: Build and push websu-api
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./build/Dockerfile_websu-api
        platforms: linux/amd64
        push: true
        tags: |
          samos123/websu-api:latest
    - name: Build and push websu-api-no-frontend
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./build/Dockerfile_websu-api-no-frontend
        platforms: linux/amd64
        push: true
        tags: |
          us-central1-docker.pkg.dev/${{ secrets.PROJECT_ID }}/websu/websu-api-no-frontend:latest
    - name: Build and push lighthouse-server-docker
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./build/Dockerfile_lighthouse-server-docker
        platforms: linux/amd64
        push: true
        tags: samos123/lighthouse-server-docker:latest
    - id: deploy
      uses: google-github-actions/deploy-cloudrun@main
      with:
        image: us-central1-docker.pkg.dev/${{ secrets.PROJECT_ID }}/websu/websu-api-no-frontend:latest
        service: websu-api
        region: us-central1
        credentials: ${{ secrets.CLOUDRUN_SA }}
